### ISSUE TITLE
Windows10 Defender

### ISSUE THREAD

**Issue by mattwhitecotten** [JasonTitcomb/Discriminator#9]
When installing, there is a pop up from Windows 10:

"Windows protected your PC.  Microsoft Defender Smartscreen prevented an unrecognized app from starting.  Running this app might put your PC at risk.  
App: setup.exe  
Publisher: MacGen Programming LLC"

This is raising questions with my IT department.  Is there any way to install this without temporarily turning off Defender?

**Comment by JasonTitcomb** [comment]
This happens when I renew my code signing certificate.
Try the suggestions below.

 Cause
Microsoft Windows SmartScreen may flag newly uploaded files that have not built up a long enough history.

Resolution
You can unblock the application by doing the following:

    Right-click on the file and select Properties.
    Under the General tab, select the Unblock checkbox next to the Security message: "This file came from another computer and might be blocked to help protect this computer."
    Click OK.

Alternatively, on the "Windows protected your PC" dialog box, you may click Run anyway.
